=== SysBind/moodle-moe/lib/xmldb/xmldb.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="FIELD">
    <xs:complexType>
      <xs:attribute name="ENUM" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="false" />
            <xs:enumeration value="true" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="LENGTH" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="DECIMALS" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="NEXT" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="SEQUENCE" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="false" />
            <xs:enumeration value="true" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="ENUMVALUES" type="xs:string" use="optional" />
      <xs:attribute name="DEFAULT" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="TYPE" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="binary" />
            <xs:enumeration value="char" />
            <xs:enumeration value="float" />
            <xs:enumeration value="int" />
            <xs:enumeration value="number" />
            <xs:enumeration value="text" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="UNSIGNED" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="false" />
            <xs:enumeration value="true" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="PREVIOUS" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="NOTNULL" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="false" />
            <xs:enumeration value="true" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="NAME" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="FIELDS">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="FIELD" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="INDEX">
    <xs:complexType>
      <xs:attribute name="PREVIOUS" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="COMMENT" type="xs:string" use="optional" />
      <xs:attribute name="UNIQUE" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="false" />
            <xs:enumeration value="true" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="NAME" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="FIELDS" type="xs:string" use="required" />
      <xs:attribute name="NEXT" type="xs:NMTOKEN" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="INDEXES">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="INDEX" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="KEY">
    <xs:complexType>
      <xs:attribute name="PREVIOUS" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="COMMENT" type="xs:string" use="optional" />
      <xs:attribute name="NAME" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="name" />
            <xs:enumeration value="plugin_name" />
            <xs:enumeration value="primary" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="FIELDS" type="xs:string" use="required" />
      <xs:attribute name="TYPE" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="primary" />
            <xs:enumeration value="unique" />
            <xs:enumeration value="foreign" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="NEXT" type="xs:NMTOKEN" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="KEYS">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="KEY" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="SENTENCE">
    <xs:complexType>
      <xs:attribute name="TEXT" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="SENTENCES">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SENTENCE" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="STATEMENT">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SENTENCES" />
      </xs:sequence>
      <xs:attribute name="COMMENT" type="xs:string" use="required" />
      <xs:attribute name="TABLE" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="NAME" type="xs:string" use="required" />
      <xs:attribute name="TYPE" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="STATEMENTS">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="STATEMENT" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="TABLE">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="FIELDS" />
        <xs:element ref="KEYS" />
        <xs:element ref="INDEXES" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="PREVIOUS" type="xs:NMTOKEN" use="optional" />
      <xs:attribute name="COMMENT" type="xs:string" use="required" />
      <xs:attribute name="NAME" type="xs:ID" use="required" />
      <xs:attribute name="NEXT" type="xs:NMTOKEN" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="TABLES">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TABLE" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="XMLDB">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TABLES" />
        <xs:element ref="STATEMENTS" />
      </xs:sequence>
      <xs:attribute name="PATH" type="xs:string" use="required" />
      <xs:attribute name="COMMENT" type="xs:string" use="required" />
      <xs:attribute name="VERSION" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== SysBind/moodle-moe/question/type/opaque/db/install.xml
<?xml version="1.0" encoding="UTF-8" ?>
<XMLDB PATH="question/type/opaque/db" VERSION="20110114" COMMENT="XMLDB file for Moodle question/type/opaque"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../lib/xmldb/xmldb.xsd"
>
  <TABLES>
    <TABLE NAME="question_opaque_engines" COMMENT="Remote engines that the Opaque question type can connect to. Each engine will comprise one or more servers stored in the question_opaque_servers table" NEXT="question_opaque_servers">
      <FIELDS>
        <FIELD NAME="id" TYPE="int" LENGTH="10" NOTNULL="true" UNSIGNED="false" SEQUENCE="true" COMMENT="id of the table, please edit me" NEXT="name"/>
        <FIELD NAME="name" TYPE="char" LENGTH="255" NOTNULL="true" SEQUENCE="false" COMMENT="The name used to identify this engine in the interface." PREVIOUS="id" NEXT="passkey"/>
        <FIELD NAME="passkey" TYPE="char" LENGTH="8" NOTNULL="false" SEQUENCE="false" COMMENT="The passkey for the QE if required." PREVIOUS="name"/>
      </FIELDS>
      <KEYS>
        <KEY NAME="primary" TYPE="primary" FIELDS="id" COMMENT="primary key of the table, please edit me"/>
      </KEYS>
    </TABLE>
    <TABLE NAME="question_opaque_servers" COMMENT="This table stores the individual servers that make up an Opaque remote engine." PREVIOUS="question_opaque_engines" NEXT="question_opaque">
      <FIELDS>
        <FIELD NAME="id" TYPE="int" LENGTH="10" NOTNULL="true" UNSIGNED="false" SEQUENCE="true" COMMENT="id of the table, please edit me" NEXT="engineid"/>
        <FIELD NAME="engineid" TYPE="int" LENGTH="10" NOTNULL="true" UNSIGNED="false" SEQUENCE="false" COMMENT="The Opaque engine this server is part of." PREVIOUS="id" NEXT="type"/>
        <FIELD NAME="type" TYPE="char" LENGTH="16" NOTNULL="true" SEQUENCE="false" COMMENT="The type of this server - question engine or question bank." PREVIOUS="engineid" NEXT="url"/>
        <FIELD NAME="url" TYPE="char" LENGTH="255" NOTNULL="true" SEQUENCE="false" COMMENT="The base URL of this server." PREVIOUS="type"/>
      </FIELDS>
      <KEYS>
        <KEY NAME="primary" TYPE="primary" FIELDS="id" COMMENT="primary key of the table, please edit me" NEXT="quesopaqserv_eng_fk"/>
        <KEY NAME="quesopaqserv_eng_fk" TYPE="foreign" FIELDS="engineid" REFTABLE="question_opaque_engines" REFFIELDS="id" PREVIOUS="primary"/>
      </KEYS>
    </TABLE>
    <TABLE NAME="question_opaque" COMMENT="Extra infomation required to define an Opaque question. This table extends the question table." PREVIOUS="question_opaque_servers">
      <FIELDS>
        <FIELD NAME="id" TYPE="int" LENGTH="10" NOTNULL="true" UNSIGNED="false" SEQUENCE="true" COMMENT="id of the table, please edit me" NEXT="questionid"/>
        <FIELD NAME="questionid" TYPE="int" LENGTH="10" NOTNULL="true" UNSIGNED="false" SEQUENCE="false" COMMENT="The id of the question this row relates to." PREVIOUS="id" NEXT="engineid"/>
        <FIELD NAME="engineid" TYPE="int" LENGTH="10" NOTNULL="true" UNSIGNED="false" SEQUENCE="false" COMMENT="The remote engine that provides this question. Refers to question_opaaque_engines.id." PREVIOUS="questionid" NEXT="remoteid"/>
        <FIELD NAME="remoteid" TYPE="char" LENGTH="255" NOTNULL="true" SEQUENCE="false" COMMENT="The id of this question - meaningful to the remote engine." PREVIOUS="engineid" NEXT="remoteversion"/>
        <FIELD NAME="remoteversion" TYPE="char" LENGTH="16" NOTNULL="true" SEQUENCE="false" COMMENT="The version of this question - meaningful to the remote engine." PREVIOUS="remoteid"/>
      </FIELDS>
      <KEYS>
        <KEY NAME="primary" TYPE="primary" FIELDS="id" COMMENT="primary key of the table, please edit me" NEXT="quesopaq_eng_fk"/>
        <KEY NAME="quesopaq_eng_fk" TYPE="foreign" FIELDS="engineid" REFTABLE="question_opaque_engines" REFFIELDS="id" PREVIOUS="primary" NEXT="quesopaq_que_fk"/>
        <KEY NAME="quesopaq_que_fk" TYPE="foreign" FIELDS="questionid" REFTABLE="question" REFFIELDS="id" PREVIOUS="quesopaq_eng_fk"/>
      </KEYS>
    </TABLE>
  </TABLES>
</XMLDB>
